### ISSUE TITLE
Visual Studio modules required

### ISSUE THREAD

**Issue by Shumaro211** [lucoiso/UEAzSpeechSampleProject#4]
I hope you can help me, I know is not related to the plugin.

When I try to run the build I have this message: the following modules are required to run this program: Microsoft Visual C++ Runtime. Do you know how can I include those files in the build or auto execute the installer?

I've seen that I can use the "Additional Command Line Arguments" and put something like this: -Prereqs=install --include="Microsoft.VisualStudio.Component.VC.Runtime.UCRT" --quiet
And in the project settings there is an option for Prerequisites directory.

**Comment by lucoiso** [comment]
You need to download Visual Studio 2022 with the module: Game Development with C++ heheheh
